"""Utils for mocking and testing"""


def mocked_login_answer(access_token: str, refresh_token: str) -> dict:
    """generats an Ayla login answer"""

    return {
        "access_token": access_token,
        "refresh_token": refresh_token,
        "expires_in": 86400,
        "role": "EndUser",
        "role_tags": [],
    }


def mocked_water_heater_properties(
    current_temp, set_temp, delta_temp, on_state
) -> dict:
    """generate a successful json payload for a specific water heater"""

    return [
        {
            "property": {
                "type": "Property",
                "name": "End",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326023,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "End",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F100",
                "base_type": "string",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "2023-06-01T18:45:53Z",
                "key": 588325978,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F100_FSTS",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": '{"8":60,"9":50,"11":55,"12":3,"13":-7,"14":60,"15":1,"16":0,"17":1,"18":336,"52":60,"54":0,"55":3,"56":60,"57":1,"58":110,"59":10,"60":1,"61":"Yes","62":0,"68":"Yes","71":0,"72":350,"73":5,"74":92,"80":4321,"90":"985 3.3","101":1,"102":1,"103":53,"104":1,"105":0,"106":0,"107":"13:00-18:50","108":"00:00-00:00","109":"00:00-00:00","111":"22:05","120":20,"121":22,"122":20,"123":21,"124":480,"125":101,"90":"985 3.3","101":1,"102":1,"103":54,"104":1,"105":0,"106":0}',
                "generated_from": "AYLA::device",
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F101",
                "base_type": "boolean",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "2023-05-31T11:16:00Z",
                "key": 588325983,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F101_SM",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": 1,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F104",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "2023-05-23T20:51:04Z",
                "key": 588326007,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F102_RMT",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": 1,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F103",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "2023-06-02T09:17:17Z",
                "key": 588325984,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F103_CWW",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": current_temp,
                "generated_from": "AYLA::device",
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F104",
                "base_type": "boolean",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "2023-06-01T13:16:01Z",
                "key": 588325994,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F104_IS",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": on_state,
                "generated_from": "AYLA::device",
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F105",
                "base_type": "boolean",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325998,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F105_SS",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F106",
                "base_type": "boolean",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325995,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F106_FS",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F107",
                "base_type": "string",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "2023-05-23T20:50:45Z",
                "key": 588325990,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F107_TS1",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": "13:00-18:50",
                "generated_from": "AYLA::device",
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F108",
                "base_type": "string",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325991,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F108_TS2",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F109",
                "base_type": "string",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325992,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F109_TS3",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F11",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "2023-05-22T18:28:48Z",
                "key": 588326021,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F11_ST",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": set_temp,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F110",
                "base_type": "string",
                "read_only": True,
                "direction": "output",
                "scope": "user",
                "data_updated_at": "2023-06-01T18:45:56Z",
                "key": 588326027,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F110_RFI",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": "00",
                "generated_from": "AYLA::device",
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F12",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "2023-05-24T05:37:32Z",
                "key": 588326006,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F12_TS",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": delta_temp,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F120",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325975,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F120_DT",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F121",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325987,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F121_EGT",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F122",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326009,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F122_AT",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F123",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325980,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F123_RAT",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F124",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326012,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F124_EEVO",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F125",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326019,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F125_CWT",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F13",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326010,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F13_DHPSAT",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F14",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326008,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F14_HTFHP",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F15",
                "base_type": "boolean",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325997,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F15_TOOOEHM",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F16",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326011,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F16_ATFSEH",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F17",
                "base_type": "boolean",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325996,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F17_TOOOEHFSF",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F18",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326017,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F18_SC",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F19",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326004,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F19_WTSTA",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F21",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325977,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F21",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F28",
                "base_type": "boolean",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326020,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F28_EMTOOEH",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F29",
                "base_type": "boolean",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326018,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F29_HPWONHM",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F31",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325974,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F31_DST",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F32",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325976,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F32_DFT",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F33",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325973,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F33_DST",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F34",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326001,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F34_MDT",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F50",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "2023-05-31T11:14:22Z",
                "key": 588325967,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F50_LPAM",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": 2,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F51",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325968,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F51",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F52",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325982,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F52",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F54",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "2023-05-30T13:46:00Z",
                "key": 588326025,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F54_EHOP",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": 1,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F55",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326026,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F55",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F56",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326024,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F56",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F57",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325989,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F57_ETPM",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F58",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325988,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F58",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F59",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325986,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F59",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F60",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325971,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F60_CDHBA",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F61",
                "base_type": "boolean",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325985,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F61",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F62",
                "base_type": "boolean",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "2023-05-26T19:59:38Z",
                "key": 588325993,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F62_TOOOPVF",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": 0,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F70",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326013,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F70_EEVOQ",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F71",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326016,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F71_EEVCM",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F72",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326014,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F72_MSEEVO",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F73",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326022,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F73_SEEVSD",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F74",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326015,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F74_SEEVDT",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F79",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325981,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F79_RGT",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F8",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325965,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F8_PSCST",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F80",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325979,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F80_P",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F85",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325999,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F85_DSTT",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F86",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326002,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F86",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F9",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325966,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F9_PVSDST",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F90",
                "base_type": "string",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326000,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F90",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F95",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325969,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F95",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F97",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325970,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F97",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F98",
                "base_type": "boolean",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588325972,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F98_T",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "F99",
                "base_type": "integer",
                "read_only": False,
                "direction": "input",
                "scope": "user",
                "data_updated_at": "null",
                "key": 588326005,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "F99",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": None,
                "generated_from": None,
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
        {
            "property": {
                "type": "Property",
                "name": "version",
                "base_type": "string",
                "read_only": True,
                "direction": "output",
                "scope": "user",
                "data_updated_at": "2023-05-23T11:50:41Z",
                "key": 588326003,
                "device_key": 2292230,
                "product_name": "DES",
                "track_only_changes": False,
                "display_name": "version",
                "host_sw_version": False,
                "time_series": False,
                "derived": False,
                "app_type": None,
                "recipe": None,
                "value": "SN0-0000000 Water_Heater W600 v2.1 Mar 22 2021 09:58:30",
                "generated_from": "AYLA::device",
                "generated_at": None,
                "denied_roles": [],
                "ack_enabled": False,
                "retention_days": 30,
            }
        },
    ]
